### ISSUE TITLE
Having problems installing and using in a .net framework 4.6.1

### ISSUE THREAD

**Issue by bstaack** [Abenity/abenity-csharp#10]
Trying to install the latest version of this (1.6.0) to a .net 4.6.1 I get an error of "You are trying to install this packaged into a project that targets .net 4.6.1 but the package does not contain any assembly references... "  This is also true when trying to install to a 4.5.2.

I am able to install an older version (1.0.3) but running the post sso member with a test member Bouncy throws an error of cannot cast 1 object to another.

I have also tried just implementing the classes found here but am getting server responded bad request.  I would like to get the nuget package working if possible.

Thanks for any response.

**Comment by markroland** [comment]
Thank you for letting me know. I will look into this and get back to you this week.

**Comment by markroland** [comment]
@halomademeapc, Can you please take a look at the issue mentioned here? I think it's related to your PR that we merged. Thank you.

@hondaguy520 I believe the 1.4 branch (https://github.com/Abenity/abenity-csharp/tree/v1.4) should be a working configuration for .net 4.5. I will do what I can to resolve this, but I'm not a .NET developer, nor do I have access to a testing environment.

**Comment by bstaack** [comment]
@markroland Thanks. I ended up using 1.5 on .net 4.5.2 successfully. Unfortunately I can not devote any time to helping you all with 1.6 issue.

**Comment by markroland** [comment]
Ok. Thanks @hondaguy520. I'm glad you found a workable solution.

**Comment by bstaack** [comment]
@markroland The sandbox api is working as expected ( as long as the response url with token does not actually log the user in)   As soon as I change to true to use production with a valid member, the server is returning 400 Bad Request. I do not see any where in the documentation on what to address.  Could you provide some insight? I would greatly appreciate it.
