### ISSUE TITLE
NuGet package v1.2.0 "assembly references" error

### ISSUE THREAD

**Issue by markroland** [Abenity/abenity-csharp#4]
Visual Studio is reporting error.

<img width="718" alt="visual-studio-nuget-error" src="https://user-images.githubusercontent.com/1097919/26893301-c6db7f26-4b6f-11e7-8fd6-2cad0994285b.png">

**Comment by dithidi** [comment]
@markroland We should be able to go ahead and close this one out.

**Comment by markroland** [comment]
Repackaged as 1.2.1. Thanks Brent!
