### ISSUE TITLE
BouncyCastle 1.8+ Not Compatible

### ISSUE THREAD

**Issue by halomakes** [Abenity/abenity-csharp#7]
Using a newer version of BouncyCastle than 1.7 does not work with the client.  You get this error upon calling PostSsoMember.
`Message: System.IO.FileLoadException: Could not load file or assembly 'BouncyCastle.Crypto, Version=1.7.4137.9688, Culture=neutral, PublicKeyToken=a4292a325f69b123' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'BouncyCastle.Crypto, Version=1.7.4137.9688, Culture=neutral, PublicKeyToken=a4292a325f69b123'
   at Abenity.Api.AbenityApi.SignMessage(String hash)
   at Abenity.Api.AbenityApi.GetApiBody()
   at Abenity.Api.AbenityApi.Post()
   at Abenity.Api.AbenityApi.PostSsoMember(SsoMemberPayload ssoMemberPayload)
   at INFB.Sitefinity.Mvc.Controllers.AbenityLinkController.Index() in ...\AbenityLinkController.cs:line 156`

Support for newer versions should be added or the NuGet package should at least correctly indicate that it specifically dependent on 1.7.0, not >=1.7.0

**Comment by markroland** [comment]
Thank you for noting this. Does your PR address this? If so, that was just merged so we can close this.

**Comment by halomakes** [comment]
Actually, I think this could have been an issue with the configuration of the site that was using it. The PR does use bouncycastle 1.8.x though so it shouldn't be an issue
